### ISSUE TITLE
Seperate Discourse API

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/wb-discord-bot#6]
Wir sollten schauen das wir die Discourse API seperieren um sie aus verschiedenen cogs ansprechen zu können. Damit könnten wir uns den Code ein bissechen sauberer halten. Evtl. wäre auch die Verwendung des [pydiscourse](https://github.com/bennylope/pydiscourse) eine Idee.

**Comment by Darksoul4626** [comment]
Eine eigene Klasse find ich gut... die Klasse von der pydiscourse Library https://github.com/bennylope/pydiscourse/blob/master/pydiscourse/client.py 
ist ganz gut.
