### ISSUE TITLE
Timer for keyword reaction

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/wb-discord-bot#7]
# ToDo: Nur alle x Tage oder alle x Meldungen darauf reagieren...

https://github.com/kreativmonkey/wb-discord-bot/blob/d709c3bb4573f51ea7b4a01c6da67feb438bf32b/cogs/reaction.py#L30-L32

**Comment by Darksoul4626** [comment]
Ist erledigt, pushe ich die Tage
